### ISSUE TITLE
ImportError: No module named whois

### ISSUE THREAD

**Issue by Jihadist** [s0md3v/Striker#33]
Something went wrong when i tried `python striker.py`

`Traceback (most recent call last):
  File "striker.py", line 11, in <module>
    import whois
ImportError: No module named whois
`

**Comment by Jihadist** [comment]
I think should add whois to requirements

**Comment by s0md3v** [comment]
Striker is being re-written and hence issues and pull requests related to the previous build no longer apply.
Thanks for contributing to the project.
