### ISSUE TITLE
Code crash at dns dump

### ISSUE THREAD

**Issue by wtf123000** [s0md3v/Striker#35]
Same issue as #32, but you closed it before I made a response.
This is the error it throws when dns dump kicks in:

Traceback (most recent call last):
  File "striker.py", line 247, in <module>
    dnsdump(domain)
  File "striker.py", line 177, in dnsdump
    res = DNSDumpsterAPI(False).search(domain)
  File "/home/fc/Striker/plugins/DNSDumpsterAPI.py", line 93, in search
    res['dns_records']['mx'] = self.retrieve_results(tables[1])
IndexError: list index out of range

**Comment by tbhaxor** [comment]
@wtf123000 will u please  share the URL ?

**Comment by s0md3v** [comment]
Striker is being re-written and hence issues and pull requests related to the previous build no longer apply.
Thanks for contributing to the project.
