### ISSUE TITLE
Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by iamkenichi** [s0md3v/Striker#38]
Arnes-MacBook-Pro:Striker Arne$ python striker.py
  File "striker.py", line 52
    \/                     \/    \/\033[1;m'''
                                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('''\033[1)?
Arnes-MacBook-Pro:Striker Arne$ python3 striker.py 
  File "striker.py", line 52
    \/                     \/    \/\033[1;m'''
                                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('''\033[1)?

**Comment by T4P4N** [comment]
use python2
