### ISSUE TITLE
not pipeable and no saved report

### ISSUE THREAD

**Issue by hydrastarmaster** [s0md3v/Striker#40]
StdOut not saved: the interactive session prevent from using ">" and "tee" in command line.

Would be far better to move "Enter the target" and "Would you like to use WPScan?" to in-line parameters, in order to make Striker pipeable.

**Comment by s0md3v** [comment]
Striker is being re-written and hence issues and pull requests related to the previous build no longer apply.
Thanks for contributing to the project.
