### ISSUE TITLE
ImportError: No module named mofa

### ISSUE THREAD

**Issue by Caleb-Huo** [s0md3v/Striker#42]
I tried to run the default example of CLL_data.
Here is the error message:

Error in py_module_import(module, convert = convert) : 
  ImportError: No module named mofa

I should have installed mofa by the following.
git clone https://github.com/bioFAM/MOFA
python setup.py install

And if I open python, I am able to import mofa by "import mofa"

What should I do?

**Comment by s0md3v** [comment]
Dude what the fuck?
"MOFA" is related to machine learning and Striker doesn't depend on it.
Looks like you are high or something.
