### ISSUE TITLE
Strange Problem

### ISSUE THREAD

**Issue by eudomoniacc** [s0md3v/Striker#43]
[+] DNS Records
Traceback (most recent call last):
  File "striker.py", line 247, in <module>
    dnsdump(domain)
  File "striker.py", line 179, in dnsdump
    for entry in res['dns_records']['dns']:

**Comment by s0md3v** [comment]
Striker v2 will be released this month.
Hang on ^_^

**Comment by SzymonZy** [comment]
Is there any workaround to use strike v1?

**Comment by htr3n** [comment]
@s0md3v got the same error for the domain github.io (tested my blog: htr3n.github.io)

```
[+] DNS Records
Traceback (most recent call last):
  File "striker.py", line 247, in <module>
    dnsdump(domain)
  File "striker.py", line 179, in dnsdump
    for entry in res['dns_records']['dns']:
TypeError: list indices must be integers, not str
```

**Comment by hougomartim** [comment]
> [+] DNS Records
> Traceback (most recent call last):
> File "striker.py", line 247, in 
> dnsdump(domain)
> File "striker.py", line 179, in dnsdump
> for entry in res['dns_records']['dns']:

use it:

https://github.com/s0md3v/Striker/pull/44/files

**Comment by nibiwodong** [comment]
There was an error getting results

[+] DNS Records
Traceback (most recent call last):
  File "striker.py", line 243, in <module>
    dnsdump(domain)
  File "striker.py", line 175, in dnsdump
    for entry in res['dns_records']['dns']:
TypeError: list indices must be integers, not str

**Comment by hougomartim** [comment]
> There was an error getting results
> 
> [+] DNS Records
> Traceback (most recent call last):
> File "striker.py", line 243, in 
> dnsdump(domain)
> File "striker.py", line 175, in dnsdump
> for entry in res['dns_records']['dns']:
> TypeError: list indices must be integers, not str

try it with http:// or https:// when typing target address.

**Comment by nibiwodong** [comment]
> > There was an error getting results
> > [+] DNS Records
> > Traceback (most recent call last):
> > File "striker.py", line 243, in
> > dnsdump(domain)
> > File "striker.py", line 175, in dnsdump
> > for entry in res['dns_records']['dns']:
> > TypeError: list indices must be integers, not str
> 
> try it with http:// or https:// when typing target address.

Maybe you target format is one of reasons. I checked the exception and found the other reason, about keyword 'error'.
see:  https://github.com/s0md3v/Striker/pull/45/files
