### ISSUE TITLE
DNS records error

### ISSUE THREAD

**Issue by SimplyPancake** [s0md3v/Striker#47]
When scanning the site 'www.atchilversum.nl', at DNS Records it outputs this:
`Traceback (most recent call last):
  File "striker.py", line 243, in <module>
    dnsdump(domain)
  File "striker.py", line 175, in dnsdump
    for entry in res['dns_records']['dns']:
TypeError: list indices must be integers, not str`

**The issue is fixed when you don't use 'www.' at the beginning of your website input.

Please specify this is the README.md**

**Comment by s0md3v** [comment]
People need to understand that www.example.com is a subdomain, not a domain.
I am not maintaining this project but I am looking forward to rewriting this.
