### ISSUE TITLE
There was an error getting results

### ISSUE THREAD

**Issue by kingxiaofire** [s0md3v/Striker#50]
There was an error getting results

[-] DNS Records
[>] Initiating 3 intel modules
[>] Loading Alpha module (1/3)
HTTPConnectionPool(host='www.google.com', port=80): Max retries exceeded with url: /search?num=100&start=0&hl=en&meta=&q=%40%22www.jsycmc.com%22 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108825190>: Failed to establish a new connection: [Errno 65] No route to host',))

how can l fix this ? l

**Comment by chaoscreater** [comment]
Got a similar thing with the "3 intel modules" error:

![image](https://user-images.githubusercontent.com/18227319/56707025-5bc04680-676b-11e9-804b-9357eeb160ae.png)

**Comment by s0md3v** [comment]
Striker is being re-written and hence issues and pull requests related to the previous build no longer apply.
Thanks for contributing to the project.
