### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by noobmonxter** [s0md3v/Striker#56]
Not able to perform scan :v
![Screenshot](https://user-images.githubusercontent.com/30261568/57133285-ef26f680-6dbf-11e9-9fd3-c3d9bc60443d.png)

**Comment by s0md3v** [comment]
Are you running it in a VM or a low spec machine?

**Comment by noobmonxter** [comment]
I've dual booted, and using Xubuntu.
I'll clean install other distro tonight.😅

**Comment by iCreepy** [comment]
Same error for me, i'm running it on a VM, any help?
