### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ATHULBABYKURIAN** [s0md3v/Striker#57]
Traceback (most recent call last):
  File "striker.py", line 37, in <module>
    raw_subdomains = list(set(findsubdomains(sys.argv[1]) + security_trails(sys.argv[1])))
IndexError: list index out of range
![image](https://user-images.githubusercontent.com/37255301/57189521-7a71ca80-6f2d-11e9-9416-f297e2dc8e57.png)

**Comment by s0md3v** [comment]
You need to supply a target e.g. `python3 striker.py example.com`

**Comment by itvodanh** [comment]
[https://drive.google.com/open?id=1Cvhx1Q3F_3XsJLe0-l_90fO8-90pL5xG](url)
[https://drive.google.com/open?id=1D7nz-JJVzmE29zwnZ-5xCqJAIxyiwkXi](url)
Hi s0md3v.
Can you help me?
Thank you
