### ISSUE TITLE
Line 61 Error

### ISSUE THREAD

**Issue by mr7Zx** [s0md3v/Striker#59]
File "striker.py", line 61
SyntaxError: Non-ASCII character '\xe2' in file striker.py on line 61, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by tweetyzero** [comment]
yeap same error here

**Comment by dkfyi** [comment]
use Python3 with this build. This issue is caused by using Python 2
`apt-get install python3`
`apt-get install python3-pip`
`pip3 install -r requirements.txt`
`python3 striker.py %yourdomain.com%`

**Comment by toxichacker420** [comment]
Anyone else getting this error ?

AbuAdams-MacBook-Pro:Striker-master AbuAdam$ python3 striker.py 
Traceback (most recent call last):
  File "striker.py", line 13, in <module>
    from core.colors import red, white, end, green, dgreen, info, good, bad, run, red_line
ImportError: cannot import name 'dgreen' from 'core.colors' (/Users/AbuAdam/Striker-master/core/colors.py)
AbuAdams-MacBook-Pro:Striker-master AbuAdam$ 




AbuAdams-MacBook-Pro:Striker-master AbuAdam$ python3 striker.py yahoo.com
Traceback (most recent call last):
  File "striker.py", line 13, in <module>
    from core.colors import red, white, end, green, dgreen, info, good, bad, run, red_line
ImportError: cannot import name 'dgreen' from 'core.colors' (/Users/AbuAdam/Striker-master/core/colors.py)
AbuAdams-MacBook-Pro:Striker-master AbuAdam$ 
AbuAdams-MacBook-Pro:Striker-master AbuAdam$ ls
LICENSE			db			striker.py
README.md		modules
core			requirements.txt
AbuAdams-MacBook-Pro:Striker-master AbuAdam$ 
AbuAdams-MacBook-Pro:Striker-master AbuAdam$ ls
LICENSE			db			striker.py
README.md		modules
core			requirements.txt
AbuAdams-MacBook-Pro:Striker-master AbuAdam$

**Comment by s0md3v** [comment]
I believe the issue has been fixed in latest update, let me know if it still exists.
