### ISSUE TITLE
it dosn't worck striker

### ISSUE THREAD

**Issue by dragon-mma** [s0md3v/Striker#61]
[^] Running component level check
[^] Starting engine
[^] Turning on radar
Traceback (most recent call last):
  File "striker.py", line 37, in <module>
    raw_subdomains = list(set(findsubdomains(sys.argv[1]) + security_trails(sys.argv[1])))
IndexError: list index out of range

**Comment by jianchen21** [comment]
same issue here

**Comment by s0md3v** [comment]
Usage: `python3 striker.py example.com`

I think you are missing the domain name.
