### ISSUE TITLE
How to scan multiple level subdomains??

### ISSUE THREAD

**Issue by jordantsap** [s0md3v/Striker#62]
LKets say that i have a website subdomainto scan i.e sub.website.com.
Maybe add a feature for level scanning like --level??
The tool has no help command either??

Maybe some usage section in read me??

**Comment by s0md3v** [comment]
Hi @jordantsap ,

Sorry for such a late response but this program is in Alpha, it is not intended to be used by actual users.
The functionality to scan subdomains will be added real soon.
