### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by davieking1** [s0md3v/Striker#63]
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by s0md3v** [comment]
Please paste the whole traceback and I will re-open this issue.

**Comment by amplenus** [comment]
[^] Running component level check
[^] Starting engine
[^] Turning on radar
Traceback (most recent call last):
  File "striker.py", line 37, in <module>
    raw_subdomains = list(set(findsubdomains(sys.argv[1]) + security_trails(sys.argv[1])))
  File "/root/Desktop/Striker/modules/security_trails.py", line 8, in security_trails
    prefixes = json.loads(re.search(r'(?m)"subdomains":(\[.*?\])', response).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by s0md3v** [comment]
This issue has been fixed in the latest update.
