### ISSUE TITLE
Error while install python striker.py 

### ISSUE THREAD

**Issue by PentesB** [s0md3v/Striker#68]
root@kali:~/Desktop/Striker# python striker.py
Traceback (most recent call last):
  File "striker.py", line 13, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse
root@kali:~/Desktop/Striker# 

please help.Thanks alot

**Comment by PentesB** [comment]
raceback (most recent call last):
  File "striker.py", line 13, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse

**Comment by ucatal** [comment]
I have the same issue with **codyalex**  (Do you have any update?)
File "striker.py", line 13, in 
from urllib.parse import urlparse
ImportError: No module named parse

**Comment by s0md3v** [comment]
run it with python3

**Comment by PentesB** [comment]
no , didnot work.
